---
- :name: kotlin-reflect.jar
  :version: ''
  :url: kotlinlang.org
  :copyright: Copyright 2000-2016 JetBrains
  :license: APACHE-2.0
  :license_text: ''
  :document_required: 'true'
- :name: kotlin-runtime-sources.jar
  :version: ''
  :url: kotlinlang.org
  :copyright: Copyright 2000-2016 JetBrains
  :license: APACHE-2.0
  :license_text: ''
  :document_required: 'true'
- :name: kotlin-runtime.jar
  :version: ''
  :url: kotlinlang.org
  :copyright: Copyright 2000-2016 JetBrains
  :license: APACHE-2.0
  :license_text: ''
  :document_required: 'true'
- :name: jsch-0.1.54.jar
  :version: 0.1.54
  :url: jcraft.com
  :copyright: Copyright 1998-2016 JCraft, Inc.
  :license: BSD
  :license_text: ''
  :document_required: 'true'
